### ISSUE TITLE
Add link in README to dataset used

### ISSUE THREAD

**Issue by nateraw** [sh-lee-prml/BigVGAN#1]
Hey there, I checked this out, but when I went to run `process.py`, my directory tree looked different than yours for VCTK. I downloaded it from [here](https://datashare.ed.ac.uk/handle/10283/3443) - the files are flac and the structure of the files is slightly different (more than one mic per each recording, etc), so it ends up throwing off the train/test splits. 

I was able to update the scripts accordingly for my use case, but it may be nice for others coming into this project. 

Which data download did you use?

**Comment by sh-lee-prml** [comment]
We used the VCTK-Corpus-0.80 version. Unfortunately, we found this version is no longer publicly available...

You can use the VCTK-Corpus-0.92 version (mic1 file is the same audio released in 0.80).

We will update the preprocessing.py for the VCTK-Corpus-0.92 version.

**Comment by sh-lee-prml** [comment]
We update the download link and preprocessing.py for the VCTK-Corpus-0.92. 

If you want to reproduce the original setting, you have to change some parts:

1. Linear spectrogram --> Mel-spectrogram with 100 bin and [fmin=0, fmax=12,000hz] for input Mel-spectrogram

2.  learning rate 0.0002 --> 0.0001

The discriminators are collapsed when using a learning rate of 0.0002 and Halving the learning rate to 0.0001 reduce this problem as described in the paper.

However, we found that 
when using the linear spectrogram as an input and a learning rate of 0.0002, the model did not show any early training collapse.

3. gradient clipping
This also reduces the above issues as described in the paper. 

4. (option) if you want to use the same spectrogram shape with HiFi-GAN, change the minimum value before torch.sqrt
(VITS uses 1e-6, and conventional vocoder uses 1e-9)
```sh
spec = torch.sqrt(spec.pow(2).sum(-1) + 1e-6) --> spec = torch.sqrt(spec.pow(2).sum(-1) + 1e-9)
```

**Comment by nateraw** [comment]
Great - this info should be enough for my needs. Thanks so much!

**Comment by skol101** [comment]
> 1. mel_fmax_for_loss

This block change (along with eps 1e-9)
```
mel = spec_to_mel_torch(
                spec,
                hps.data.filter_length,
                hps.data.n_mel_channels,
                hps.data.sampling_rate,
                hps.data.mel_fmin,
                hps.data.mel_fmax)

        mel_for_loss = spec_to_mel_torch(
                spec,
                hps.data.filter_length,
                hps.data.n_mel_channels,
                hps.data.sampling_rate,
                hps.data.mel_fmin,
                hps.data.mel_fmax_for_loss)
```
 leads to error

```
RuntimeError: Given groups=1, weight of size [512, 513, 7], expected input[16, 80, 32] to have 513 channels, but got 80 channels instead
```
IT'd be nice if it was actually possible to test with MEL spectrogram.
