### ISSUE TITLE
Can this be used as a substitute for HifiGan for VC task?

### ISSUE THREAD

**Issue by skol101** [sh-lee-prml/BigVGAN#2]
Could you provide inference example?

**Comment by sh-lee-prml** [comment]
I will update inference code soon. 

```sh

import os
import torch
import argparse

from glob import glob
import tqdm
import numpy as np
from scipy.io.wavfile import write
import utils


from mel_processing import mel_spectrogram_torch
from models_bigvgan import Generator

h = None
device = None

def get_mel(x):
    return mel_spectrogram_torch(x, h.n_fft, h.num_mels, h.sampling_rate, h.hop_size, h.win_size, h.fmin, h.fmax)

def load_checkpoint(filepath, device):
    assert os.path.isfile(filepath)
    print("Loading '{}'".format(filepath))
    checkpoint_dict = torch.load(filepath, map_location=device)
    print("Complete.")
    return checkpoint_dict

def scan_checkpoint(cp_dir, prefix):
    pattern = os.path.join(cp_dir, prefix + '*')
    cp_list = glob.glob(pattern)
    if len(cp_list) == 0:
        return ''
    return sorted(cp_list)[-1]

def inference(a):

    os.makedirs(a.output_dir, exist_ok=True)

    generator = Generator(h).to(device)
    state_dict_g = load_checkpoint(a.checkpoint_file, device)

    generator.load_state_dict(state_dict_g['generator'])
    generator.eval()
    generator.remove_weight_norm()

    npz_path = glob(os.path.join(a.input_dir, os.path.join("test", "*.npz")))

    print("data len: ", len(npz_path))


    i = 0
    for path in tqdm.tqdm(npz_path, desc="synthesizing each utterance"):

        files = np.load(path)
        file_name = os.path.splitext(os.path.basename(path))[0]

        with torch.no_grad():
            audio = torch.FloatTensor(files['audio'])
            audio = audio.to(device)
            audio = audio / 32768
            mel = get_mel(audio.unsqueeze(0))
            audio= generator(mel)

            audio = audio.squeeze()
            audio = audio / (torch.abs(audio).max()) * 0.999 * 32768.0
            audio = audio.cpu().numpy().astype('int16')

            file_name = "generated_{}.wav".format(file_name)
            output_file = os.path.join(a.output_dir, file_name)
            write(output_file, 22050, audio)


def main():
    print('Initializing Inference Process..')

    parser = argparse.ArgumentParser()
    parser.add_argument('--input_dir', default='')
    parser.add_argument('--output_dir', default='inference/')
    parser.add_argument('--checkpoint_file', default='logs/checkpoint')
    a = parser.parse_args()


    config_file = os.path.join(os.path.split(a.checkpoint_file)[0], 'config.json')

    global h

    h = utils.get_hparams_from_file(config_file)

    torch.manual_seed(1234)
    global device
    if torch.cuda.is_available():
        torch.cuda.manual_seed(1234)
        device = torch.device('cuda')
    else:
        device = torch.device('cpu')

    inference(a)

if __name__ == '__main__':
    main()

```

**Comment by skol101** [comment]
I'm experiementing with StarGANv2-VC, where we can use one of ParallelWaveGan trained vocoders. 
```python

# load vocoder
from parallel_wavegan.utils import load_model
vocoder = load_model("Vocoder/checkpoint-400000steps.pkl").to('cuda').eval()
vocoder.remove_weight_norm()
_ = vocoder.eval()

 f0_feat = F0_model.get_feature_GAN(source.unsqueeze(1))
        out = starganv2.generator(source.unsqueeze(1), ref, F0=f0_feat)
        
        c = out.transpose(-1, -2).squeeze().to('cuda')
        y_out = vocoder.inference(c)
        y_out = y_out.view(-1).cpu()
````

That's where I'm wondering about replace in-place of vocoder.inference with BigVGAN vocoder, assuming it's trained on the same dataset.

**Comment by sh-lee-prml** [comment]
If you use the same Mel-spectrogram for vocoder training, I think it will works!

**Comment by skol101** [comment]
As I understand these params must match:
```
 "sampling_rate": 22050,
    "filter_length": 1024,
    "hop_length": 256,
    "win_length": 1024,
```

In StarGanv2-VC
```
sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300
```

**Comment by sh-lee-prml** [comment]
Yes. Additionally, 

```sh
    "n_mel_channels": 80,
    "mel_fmin": 0.0,
    "mel_fmax": 
``` 

Also, above params must match.

**Comment by sh-lee-prml** [comment]
yes they are the same parameter...!

**Comment by skol101** [comment]
> Also, above params must match.
> spec = torch.sqrt(spec.pow(2).sum(-1) + 1e-6) 

What is this function used for? In Stargan VC there's log normalisation through
```
mel_tensor = (torch.log(1e-5 + mel_tensor) - self.mean) / self.std
```

**Comment by skol101** [comment]
Also, when using these params 
```
 "max_wav_value": 32768.0,
    "sampling_rate": 24000,
    "filter_length": 2048,
    "hop_length": 300,
    "win_length": 1200,
    "n_mel_channels": 80,
```
I get the error 
```
BigVGAN/train_bigvgan_vocoder.py:194: UserWarning: Using a target size (torch.Size([16, 80, 23])) that is different to the input size (torch.Size([16, 80, 27])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss_mel = F.l1_loss(y_mel, y_hat_mel) * hps.train.c_mel

```
I understand this has to do with the changed hop_size, and  "segment_size": 8192 ?

**Comment by sh-lee-prml** [comment]
> > Also, above params must match.
> > spec = torch.sqrt(spec.pow(2).sum(-1) + 1e-6)
> 
> What is this function used for? In Stargan VC there's log normalisation through
> 
> ```
> mel_tensor = (torch.log(1e-5 + mel_tensor) - self.mean) / self.std
> ```
  https://github.com/sh-lee-prml/BigVGAN/blob/main/mel_processing.py#L107

**Comment by sh-lee-prml** [comment]
> Also, when using these params
> 
> ```
>  "max_wav_value": 32768.0,
>     "sampling_rate": 24000,
>     "filter_length": 2048,
>     "hop_length": 300,
>     "win_length": 1200,
>     "n_mel_channels": 80,
> ```
> 
> I get the error
> 
> ```
> BigVGAN/train_bigvgan_vocoder.py:194: UserWarning: Using a target size (torch.Size([16, 80, 23])) that is different to the input size (torch.Size([16, 80, 27])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
>   loss_mel = F.l1_loss(y_mel, y_hat_mel) * hps.train.c_mel
> ```
> 
> I understand this has to do with the changed hop_size, and "segment_size": 8192 ?

Yes~ change 32*300 = 9600 (segmen_size) but you have to check your GPU Memory first. Modify it for your dataset~!

**Comment by skol101** [comment]
We have RTX 3090 (24gb), after chaning to 9600, still the same error albeit with different target and input sizes:
Using a target size (torch.Size([16, 80, 27])) that is different to the input size (torch.Size([16, 80, 32]))

**Comment by sh-lee-prml** [comment]
Oh... I missed some points about hop length and upsampling rates of your data... I think you have to change your upsampling rate (e.g., 6x5x5x2=300). In the original setting, the model upsamples the Mel-spectrogram to waveform by 256x (8x8x2x2=256) upsampling. 

Also, before reproducing any models for TTS or VC or vocoder, I think we have to know about data which we use...

I recommend that you check how to make Mel-spectrogram before training some models.

**Comment by sh-lee-prml** [comment]
> Our dataset is VCTK-like dataset, the only difference is that is sampling rate is 24000.

Could you check the shape of spec.pt?? I suspect that you may use the old spec.pt preprocessed by our version.

In this case, you remove your pt files first. After that, train again

**Comment by skol101** [comment]
I've decided to train only with sample_rate of 24000, all other params are the same. The model is being trained.

**Comment by skol101** [comment]
I've prepared datase with above params. Now training terminates with error
```
BigVGAN/losses.py", line 15, in feature_loss
    loss += torch.mean(torch.abs(rl - gl))
RuntimeError: The size of tensor a (192) must match the size of tensor b (193) at non-singleton dimension 3
```

**Comment by sh-lee-prml** [comment]
Actually, I have not tried this with sampling rate 24000 with hop size of 300

I think that you also change the kernel size for padding size and change initial-freq for your sampling rate 
```sh
    "upsample_rates": [5,5,4,3],
    "upsample_kernel_sizes": [11,11,8,7],
    
     initial_freq = [400, 2000, 8000, 24000] 
```

**Comment by skol101** [comment]
> ```shell
> FloatTens
> ```

Something is wrong with inference code
```python
state_dict_g = load_checkpoint("BigVGAN/logs/bigvgan_22k/G_65000.pth", device)
for key in state_dict_g:
    print(key)
generator.load_state_dict(state_dict_g['generator'])
```
results in 
```
Unexpected key(s) in state_dict: "model", "iteration", "optimizer", "learning_rate". 
```

**Comment by skol101** [comment]
Also, minor issues like prefix "dec.", there's no key 'generator' in the dictionary, but 'model'.

**Comment by sh-lee-prml** [comment]
> > ```shell
> > FloatTens
> > ```
> 
> Something is wrong with inference code
> 
> ```python
> mel_outputs = model.inference(audio_A, mel_A, mel_len_A, audio_B, mel_B, mel_len_B)
> ...
> generator = Generator(h.data.filter_length // 2 + 1,
>             h.model.resblock_kernel_sizes,h.model.resblock_dilation_sizes, h.model.upsample_rates, h.model.upsample_initial_channel, h.model.upsample_kernel_sizes).to(device)
> state_dict_g = load_checkpoint("BigVGAN/logs/bigvgan_22k/G_140000.pth", device)
> generator.load_state_dict(state_dict_g)
> generator.eval()
> generator.remove_weight_norm()
> 
> with torch.no_grad():
>     #audio = torch.FloatTensor(converted_mel)
>     #audio = audio.to(device)
>     #audio = audio / 32768
>     #mel = get_mel(audio.unsqueeze(0))
>     audio= generator(mel_outputs)
> ```
> 
> results in
> 
> ```
> RuntimeError: Given groups=1, weight of size [512, 513, 7], expected input[1, 477, 80] to have 513 channels, but got 477 channels instead
> ```
> 
> This model that generates mel_outputs works fine with its own vocoder that uses the same code to generate mel_spec as your repo https://github.com/intory89/StyleVC/blob/eb0bcf54bb06812e0f13788253f61f38a24585b6/vocoder/meldataset_custom.py#L50



> > ```shell
> > FloatTens
> > ```
> 
> Something is wrong with inference code
> 
> ```python
> mel_outputs = model.inference(audio_A, mel_A, mel_len_A, audio_B, mel_B, mel_len_B)
> ...
> generator = Generator(h.data.filter_length // 2 + 1,
>             h.model.resblock_kernel_sizes,h.model.resblock_dilation_sizes, h.model.upsample_rates, h.model.upsample_initial_channel, h.model.upsample_kernel_sizes).to(device)
> state_dict_g = load_checkpoint("BigVGAN/logs/bigvgan_22k/G_140000.pth", device)
> generator.load_state_dict(state_dict_g)
> generator.eval()
> generator.remove_weight_norm()
> 
> with torch.no_grad():
>     #audio = torch.FloatTensor(converted_mel)
>     #audio = audio.to(device)
>     #audio = audio / 32768
>     #mel = get_mel(audio.unsqueeze(0))
>     audio= generator(mel_outputs)
> ```
> 
> results in
> 
> ```
> RuntimeError: Given groups=1, weight of size [512, 513, 7], expected input[1, 477, 80] to have 513 channels, but got 477 channels instead
> ```
> 
> This model that generates mel_outputs works fine with its own vocoder that uses the same code to generate mel_spec as your repo https://github.com/intory89/StyleVC/blob/eb0bcf54bb06812e0f13788253f61f38a24585b6/vocoder/meldataset_custom.py#L50

Change the input size of filter which you choose (linear: 513, Mel: 80) and transpose your input shape. Then, it will work. 
```sh
Generator(h.data.filter_length // 2 + 1,...)
```

**Comment by sh-lee-prml** [comment]
> Also, minor issues:
> 
> * prefix "dec."for each weight and bias
> * there's no key 'generator' in the dictionary, but 'model'.



> Also, minor issues:
> 
> * prefix "dec."for each weight and bias
> * there's no key 'generator' in the dictionary, but 'model'.

Thank you. I will change it soon

**Comment by skol101** [comment]
Thanks to your suggestions I'm now able to train on 24k dataset, but your comment on changing the filter length isn't clear.

>>Change the input size of filter which you choose (linear: 513, Mel: 80) and transpose your input shape. Then, it will work.

Generator(h.data.filter_length // 2 + 1,...) 

Model trained on sample rate 24000 with filter length of 2048 will have the following weights with sizes:
 conv_pre.weight  torch.Size([512, 1025, 7])

So how do we change the mel outputs from the VC model that will be acceptable to the BigVGAN's generator?

**Comment by skol101** [comment]
I see -- the spec that is created in preprocessing should be done with the same params as in the VC model.

**Comment by skol101** [comment]
I've changed part of get_audio from your code to 
```python
MEL_PARAMS = {
    "sample_rate": sample_rate,
    "n_mels": 80,
    "n_fft": 2048,
    "win_length": 1200,
    "hop_length": 300
}
...
spec =torchaudio.transforms.MelSpectrogram(**MEL_PARAMS)
```
But when trying to train the error is the same as with inference:
```
  File "/home/sk/work/BigVGAN/models_bigvgan.py", line 121, in forward
    x = self.conv_pre(x)
  File "/home/sk/anaconda3/envs/vc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sk/anaconda3/envs/vc/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 301, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/sk/anaconda3/envs/vc/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 297, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [512, 1025, 7], expected input[16, 80, 32] to have 1025 channels, but got 80 channels instead
```

**Comment by sh-lee-prml** [comment]
As you mentioned, the hyperparameters of spectrogram for your VC model and vocoder must be same.

In this repository, I use the linear spectrogram as an input so the input size of network is  "h.data.filter_length // 2 + 1".

In your case using Mel-spectrogram with 80 bins, you should change some hyperparameter for your model...

**Comment by skol101** [comment]
The original paper made me think BigVGan is based on Hifigan, and thus should be pretty straightforward to try out as a vocoder.  Any particular reason to use linear spectrogram?

**Comment by skol101** [comment]
Well, I think just changing the hyper params isn't enough -- the VC model must be changed to use linear spectrogram.

**Comment by sh-lee-prml** [comment]
Yes... that's what i said 

All hyperparameters including what the model uses Mel or Linear spectrogram must be same.

**Comment by skol101** [comment]
Reading the paper they have based their model on Hifigan, which use Mel spectrogram, correct? 

AFAIK, most vocoders use mel spectrograms, therefore it's easy to switch between different vocoders to test them out.

**Comment by sh-lee-prml** [comment]
You are right. Most vocoders use mel-spectrogram.

Refer to this issue for Mel-spectrogram 
(https://github.com/sh-lee-prml/BigVGAN/issues/1)

There are many options for speech processing and I usually use linear spectrogram for end-to-end text-to-speech.

**Comment by skol101** [comment]
Ty for pointing me to the right issue. That's actually what I needed)
