### ISSUE TITLE
correct eps value?

### ISSUE THREAD

**Issue by skol101** [sh-lee-prml/BigVGAN#4]
Configuration json contains value of eps as 1e-9.

In the transformers.py there's
def searchsorted(bin_locations, inputs, eps=1e-6):

Whilst in another issue you say that spec must be (and eps as 1e-6)
spec = torch.sqrt(spec.pow(2).sum(-1) + 1e-6)

**Comment by sh-lee-prml** [comment]
The eps in config files is a hyperparameter for AdamW optimizer.

We followed the value for spec which is used in VITS. (1e-6).
(most vocoders use the value of 1e-9)

You can use any value for spec but must use the same option for your TTS/VC model and vocoder.
